---
name: Container Image Publishing

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Configure git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Extract version
        run: |
          echo ::set-env name=PKG_VERSION::$(cat VERSION | head -1)
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:${{ env.PKG_VERSION }},\
            ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:latest"
          platforms: linux/amd64,linux/arm64
          cache-from: "type=registry,\
            ref=ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:latest"
          cache-to: type=inline
